3ischools 20192012/KS_SmartChild/Controllers/ReportController.cs
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using BAL.BAL.Common;
using BAL.BAL.Reporting;
using DAL.DAL.ActivityLogModule;
using DAL.DAL.CatalogMaster;
using DAL.DAL.Common;
using DAL.DAL.ErrorLogModule;
using DAL.DAL.ReportingModule;
using DAL.DAL.SettingService;
using DAL.DAL.UserModule;
using KSModel.Models;
using ViewModel.ViewModel.Reporting;
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net.Mime;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace KS_SmartChild.Controllers
{
    public class ReportController : Controller
    {
        #region fields

        public int count;
        private readonly IConnectionService _IConnectionService;
        private readonly IUserService _IUserService;
        private readonly ILogService _Logger;
        private readonly ICatalogMasterService _ICatalogMasterService;
        private readonly IWebHelper _WebHelper;
        private readonly ISchoolSettingService _ISchoolSettingService;
        private readonly IReportService _IReportService;
        private readonly ICustomEncryption _ICustomEncryption;
        private readonly IActivityLogMasterService _IActivityLogMasterService;
        private readonly IActivityLogService _IActivityLogService;
        private readonly IDropDownService _IDropDownService;
        private readonly IReportingLogicService _IReportingLogicService;
        
        #endregion

        #region ctor

        public ReportController(IConnectionService IConnectionService,
            ILogService Logger,
            IUserService IUserService,
            ICatalogMasterService ICatalogMasterService,
            IWebHelper WebHelper,
            ISchoolSettingService ISchoolSettingService,
            IReportService IReportService,
            ICustomEncryption ICustomEncryption,
            IActivityLogMasterService IActivityLogMasterService,
            IActivityLogService IActivityLogService,
            IDropDownService IDropDownService,
            IReportingLogicService IReportingLogicService)
        {
            count = 0;
            this._IConnectionService = IConnectionService;
            this._IUserService = IUserService;
            this._Logger = Logger;
            this._ICatalogMasterService = ICatalogMasterService;
            this._WebHelper = WebHelper;
            this._ISchoolSettingService = ISchoolSettingService;
            this._IReportService = IReportService;
            this._ICustomEncryption = ICustomEncryption;
            this._IActivityLogMasterService = IActivityLogMasterService;
            this._IActivityLogService = IActivityLogService;
            this._IDropDownService = IDropDownService;
            this._IReportingLogicService = IReportingLogicService;
        }

        #endregion

        #region utility

        public void SetSessionData(string name)
        {
            var user = _IUserService.GetUserByEmail(name);
            HttpContext.Session["UserId"] = user.UserName;

            var logininfo = _IUserService.GetAllUserLoginInfos(ref count, user.UserId).LastOrDefault();
            if (logininfo != null)
                HttpContext.Session["LoginInfoId"] = logininfo.LoginInfoId;
        }

        public string ConvertDate(DateTime Date)
        {
            string sdisplayTime = Date.ToString("dd/MM/yyyy");
            return sdisplayTime;
        }

        public string ConvertTime(TimeSpan time)
        {
            TimeSpan timespan = new TimeSpan(time.Hours, time.Minutes, time.Seconds);
            DateTime datetime = DateTime.Today.Add(timespan);
            string sdisplayTime = datetime.ToString("hh:mm tt");
            return sdisplayTime;
        }

        #endregion

        #region methods

        // Standard Report
        //List
        public List<StandardReportModel> preparerptlistmodel(List<StandardReportModel> model)
        {
            // get all report master
            var reports = _IReportService.GetAllRptMasters(ref count);
            foreach (var item in reports)
            {
                StandardReportModel StandardReportModel = new StandardReportModel();
                StandardReportModel.EncRptMasterId = _ICustomEncryption.base64e(item.RptMasterId.ToString());
                StandardReportModel.CreateDate = item.CreationDate.HasValue ? ConvertDate(item.CreationDate.Value) : "NA";
                StandardReportModel.Status = item.IsActive != null ? item.IsActive == true ? "Yes" : "No" : "No";
                StandardReportModel.RptGenericName = item.GenericName != null ? item.GenericName : "NA";
                StandardReportModel.RptMasterName = item.ReportName;
                StandardReportModel.IsStdViewReport = false;
                StandardReportModel.IsGenViewReport = false;
                if(item.RptGenericCols.Count > 0 )
                    StandardReportModel.IsGenViewReport = true;
                if (item.RptStandardCols.Count > 0)
                    StandardReportModel.IsStdViewReport = true;

                model.Add(StandardReportModel);
            }

            return model;
        }

        public ActionResult ReportList()
        {
            SchoolUser user = new SchoolUser();
            // current user
            if (HttpContext.Session["SchoolDB"] != null)
            {
                // re-assign session
                var sessiondb = HttpContext.Session["SchoolDB"];
                HttpContext.Session["SchoolDB"] = sessiondb;

                user = System.Web.HttpContext.Current.User.Identity.Name != "" ? _IUserService.GetUserByEmail(System.Web.HttpContext.Current.User.Identity.Name) : null;
                if (user == null)
                    return RedirectToAction("Login", "Home");
                SetSessionData(System.Web.HttpContext.Current.User.Identity.Name);
            }
            else
            {
                // get action name
                var UserRequest = _WebHelper.GetControllerandActionNameFromUrl(HttpContext.Request.Url.ToString());
                return RedirectToAction("DummyAction", "Common", new { ctrl = UserRequest.ContollerName, act = UserRequest.ActionName });
            }

            try
            {
                var model = new List<StandardReportModel>();
                model = preparerptlistmodel(model);
                return View(model);
            }
            catch (Exception ex)
            {
                _Logger.InsertLog(LogLevel.Error, ex.Message, ex.StackTrace, user);
                return RedirectToAction("General", "Error");
            }
        }

        // Add Standard Report
        public ActionResult SetStandardReports()
        {
            SchoolUser user = new SchoolUser();
            // current user
            if (HttpContext.Session["SchoolDB"] != null)
            {
                // re-assign session
                var sessiondb = HttpContext.Session["SchoolDB"];
                HttpContext.Session["SchoolDB"] = sessiondb;

                user = System.Web.HttpContext.Current.User.Identity.Name != "" ? _IUserService.GetUserByEmail(System.Web.HttpContext.Current.User.Identity.Name) : null;
                if (user == null)
                    return RedirectToAction("Login", "Home");
                SetSessionData(System.Web.HttpContext.Current.User.Identity.Name);
            }
            else
            {
                // get action name
                var UserRequest = _WebHelper.GetControllerandActionNameFromUrl(HttpContext.Request.Url.ToString());
                return RedirectToAction("DummyAction", "Common", new { ctrl = UserRequest.ContollerName, act = UserRequest.ActionName });
            }

            try
            {
                var model = new StandardReportModel();
                model = prepareupdatestdrptmodel(model);
                return View(model);
            }
            catch (Exception ex)
            {
                _Logger.InsertLog(LogLevel.Error, ex.Message, ex.StackTrace, user);
                return RedirectToAction("General", "Error");
            }
        }

        public StandardReportModel checkstdreporterror(StandardReportModel model)
        {
            if (string.IsNullOrEmpty(model.RptMasterName))
                ModelState.AddModelError("RptMasterName", "Report name required");
            if (string.IsNullOrEmpty(model.RptStoredProcedureName))
                ModelState.AddModelError("RptStoredProcedureName", "Stored procedure name required");

            return model;
        }

        [HttpPost]
        public ActionResult SetStandardReports(StandardReportModel model)
        {
            SchoolUser user = new SchoolUser();
            // current user
            if (HttpContext.Session["SchoolDB"] != null)
            {
                // re-assign session
                var sessiondb = HttpContext.Session["SchoolDB"];
                HttpContext.Session["SchoolDB"] = sessiondb;

                user = System.Web.HttpContext.Current.User.Identity.Name != "" ? _IUserService.GetUserByEmail(System.Web.HttpContext.Current.User.Identity.Name) : null;
                if (user == null)
                    return RedirectToAction("Login", "Home");
                SetSessionData(System.Web.HttpContext.Current.User.Identity.Name);
            }
            else
            {
                // get action name
                var UserRequest = _WebHelper.GetControllerandActionNameFromUrl(HttpContext.Request.Url.ToString());
                return RedirectToAction("DummyAction", "Common", new { ctrl = UserRequest.ContollerName, act = UserRequest.ActionName });
            }

            try
            {
                model = checkstdreporterror(model);
                if (ModelState.IsValid)
                {
                    string message = "";
                    // Activity log type add , edit

3ischools 20192012/KS_SmartChild/Views/Report/EditGenericReports.cshtml
@model ViewModel.ViewModel.Reporting.GenericReportModel

@{
    ViewBag.Title = "Edit Generic Report";
}

<!-- Page Heading -->
<div class="row top-space-10 page-heading">
    @if (TempData["ErrorNotification"] != null && TempData["ErrorNotification"] != "")
    {
        <div class="col-md-12">
            <div class="error_notification"><i class="fa fa-ban"></i> @TempData["ErrorNotification"]</div>
        </div>
    }
    @if (TempData["SuccessNotification"] != null && TempData["SuccessNotification"] != "")
    {
        <div class="col-md-12">
            <div class="success_notification"><i class="fa fa-check"></i> @TempData["SuccessNotification"]</div>
        </div>
    }
    <div class="col-md-6">
        <h1>Edit Generic Report <span style="font-size: 11px">( <i style="color: red;font-size: 8px;" class="fa fa-asterisk"></i> fields are required )</span></h1>
    </div>
    <div class="col-md-6 text-right">
        <a href="@Html.Raw(Url.Action("GenericReportList", "Report"))" class="btn btn-xs btn-default">back</a>
    </div>
</div>
<!-- //Page Heading -->
<!-- Page Controls -->
<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("SetGenericReports", "Report", FormMethod.Post, new { @class = "form-horizontal ks-custom-form" }))
        {
            @Html.AntiForgeryToken()
            @Html.Partial("_CreateOrUpdateGenericReport", Model)
        }
    </div>
</div>

3ischools 20192012/KS_SmartChild/Views/Report/EditStandardReports.cshtml
@model ViewModel.ViewModel.Reporting.StandardReportModel

@{
    ViewBag.Title = "Edit Report";
}

<!-- Page Heading -->
<div class="row top-space-10 page-heading">
    @if (TempData["ErrorNotification"] != null && TempData["ErrorNotification"] != "")
    {
        <div class="col-md-12">
            <div class="error_notification"><i class="fa fa-ban"></i> @TempData["ErrorNotification"]</div>
        </div>
    }
    @if (TempData["SuccessNotification"] != null && TempData["SuccessNotification"] != "")
    {
        <div class="col-md-12">
            <div class="success_notification"><i class="fa fa-check"></i> @TempData["SuccessNotification"]</div>
        </div>
    }
    <div class="col-md-6">
        <h1>Edit Standard Report <span style="font-size: 11px">( <i style="color: red;font-size: 8px;" class="fa fa-asterisk"></i> fields are required )</span></h1>
    </div>
    <div class="col-md-6 text-right">
        <a href="@Html.Raw(Url.Action("ReportList", "Report"))" class="btn btn-xs btn-default">back</a>
    </div>
</div>
<!-- //Page Heading -->
<!-- Page Controls -->
<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("SetStandardReports", "Report", FormMethod.Post, new { @class = "form-horizontal ks-custom-form" }))
        {
            @Html.AntiForgeryToken()
            @Html.Partial("_CreateOrUpdate", Model)
        }
    </div>
</div>

3ischools 20192012/KS_SmartChild/Views/Report/GenericReportList.cshtml
@model IEnumerable<ViewModel.ViewModel.Reporting.StandardReportModel>

@{
    ViewBag.Title = "Manage Generic Reports";
}

<!-- Page Heading -->
<div class="row top-space-10 page-heading">
    <div class="col-md-6">
        <h1>Manage Generic Reports</h1>
    </div>
</div>
<!-- //Page Heading -->
<!-- Page Controls -->
<div class="row top-space-10">
    <div class="col-md-12">
        <table id="table-student-grid" class="table table-bordered table-condensed table-responsive table-striped">
            <thead class="thead-default">
                <tr>
                    <th class="">Report Name</th>
                    <th class="">Generic Name</th>
                    <th class="">Created Date</th>
                    <th class="text-center">IsActive</th>
                    <th class="text-center">Action</th>
                </tr>
            </thead>
            <tbody>
                @{
                    foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.RptMasterName</td>
                            <td>@item.RptGenericName</td>
                            <td>@item.CreateDate</td>
                            <td class="text-center">@item.Status</td>
                            <td class="text-center">
                                <a style="margin-right: 10px" href="@Html.Raw(Url.Action("EditGenericReports", "Report", new { id = item.EncRptMasterId }))" class="btn btn-default btn-xs" title="Edit Report" data-toggle="tooltip" data-placement="top"><i class="fa fa-pencil"></i></a>
                                @if (item.IsGenViewReport)
                                {
                                    <a href="@Html.Raw(Url.Action("ViewGenericReport", "Report", new { id = item.EncRptMasterId }))" class="btn btn-default btn-xs" title="Edit Report" data-toggle="tooltip" data-placement="top"><i class="fa fa-eye"></i></a>
                                }
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>
<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    });
</script>

3ischools 20192012/KS_SmartChild/Views/Report/ReportList.cshtml
@model IEnumerable<ViewModel.ViewModel.Reporting.StandardReportModel>

@{
    ViewBag.Title = "Manage Standard Reports";
}

<!-- Page Heading -->
<div class="row top-space-10 page-heading">
    <div class="col-md-6">
        <h1>Manage Standard Reports</h1>
    </div>
    <div class="col-md-6 text-right">
        <a href="@Html.Raw(Url.Action("SetStandardReports", "Report"))" class="btn btn-xs btn-default">Add New Report</a>
    </div>
</div>
<!-- //Page Heading -->
<!-- Page Controls -->
<div class="row top-space-10">
    <div class="col-md-12">
        <table id="table-student-grid" class="table table-bordered table-condensed table-responsive table-striped">
            <thead class="thead-default">
                <tr>
                    <th class="">Report Name</th>
                    <th class="">Generic Name</th>
                    <th class="">Created Date</th>
                    <th class="text-center">IsActive</th>
                    <th class="text-center">Action</th>
                </tr>
            </thead>
            <tbody>
                @{
                    foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.RptMasterName</td>
                            <td>@item.RptGenericName</td>
                            <td>@item.CreateDate</td>
                            <td class="text-center">@item.Status</td>
                            <td class="text-center">
                                <a style="margin-right: 10px" href="@Html.Raw(Url.Action("EditStandardReports", "Report", new { id = item.EncRptMasterId }))" class="btn btn-default btn-xs" title="Edit Report" data-toggle="tooltip" data-placement="top"><i class="fa fa-pencil"></i></a>
                                @if (item.IsStdViewReport) 
                                { 
                                    <a href="@Html.Raw(Url.Action("ViewStandardReport", "Report", new { id = item.EncRptMasterId }))" class="btn btn-default btn-xs" title="Edit Report" data-toggle="tooltip" data-placement="top"><i class="fa fa-eye"></i></a>
                                }
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>
<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    });
</script>

3ischools 20192012/KS_SmartChild/Views/Report/SetStandardReports.cshtml
@model ViewModel.ViewModel.Reporting.StandardReportModel

@{
    ViewBag.Title = "Add Report";
}

<!-- Page Heading -->
<div class="row top-space-10 page-heading">
    @if (TempData["ErrorNotification"] != null && TempData["ErrorNotification"] != "")
    {
        <div class="col-md-12">
            <div class="error_notification"><i class="fa fa-ban"></i> @TempData["ErrorNotification"]</div>
        </div>
    }
    @if (TempData["SuccessNotification"] != null && TempData["SuccessNotification"] != "")
    {
        <div class="col-md-12">
            <div class="success_notification"><i class="fa fa-check"></i> @TempData["SuccessNotification"]</div>
        </div>
    }
    <div class="col-md-6">
        <h1>Add Standard Report <span style="font-size: 11px">( <i style="color: red;font-size: 8px;" class="fa fa-asterisk"></i> fields are required )</span></h1>
    </div>
    <div class="col-md-6 text-right">
        <a href="@Html.Raw(Url.Action("ReportList", "Report"))" class="btn btn-xs btn-default">back</a>
    </div>
</div>
<!-- //Page Heading -->
<!-- Page Controls -->
<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("SetStandardReports", "Report", FormMethod.Post, new { @class = "form-horizontal ks-custom-form" }))
        {
            @Html.AntiForgeryToken()
            @Html.Partial("_CreateOrUpdate", Model)
        }
    </div>
</div>

3ischools 20192012/KS_SmartChild/Views/Report/ViewGenericReport.cshtml
@model ViewModel.ViewModel.Reporting.ViewReportModel

@{
    ViewBag.Title = "View Report";
}

<!-- Page Heading -->
<div class="row top-space-10 page-heading">
    <div class="col-md-6">
        <h1>View Report</h1>
    </div>
    <div class="col-md-6 text-right">
        <a href="@Html.Raw(Url.Action("GenericReportList", "Report"))" class="btn btn-xs btn-default">back</a>
    </div>
</div>
<!-- //Page Heading -->
<!-- Page Controls -->
@using (Html.BeginForm("ViewGenericReport", "Report", FormMethod.Post, new { @class = "form-inline ks-custom-form" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ReportMasterId)
    @Html.HiddenFor(model => model.Grid)

    <div class="row top-space-10">
        @{
    foreach (var item in Model.ReportControlsList)
    {
        <div class="form-group">
            <label>@item.Label</label>
            @if (item.ControlTypeDisplayName.Contains("Text Box"))
            {
                @Html.TextBox(item.Label, null, new { @class = "form-control" })
            }
            @if (item.ControlTypeDisplayName.Contains("Drop Down"))
            {
                @Html.DropDownList(item.Label, item.selectlist, new { @class = "form-control" })
            }
            @if (item.ControlTypeDisplayName.Contains("Date"))
            {
                @Html.TextBox(item.Label, null, new { @class = "datepicker" })
            }
            @if (item.ControlTypeDisplayName.Contains("Time"))
            {
                @Html.TextBox(item.Label, null, new { @class = "form-control timepicker" })
            }
        </div>
    }
        }

        <div class="form-group">
            <input type="submit" name="submit" value="Filter" id="fltr_btn" class="btn btn-default" />
            @if (Model.RowList.Count > 0)
            {
                <input type="button" name="export" value="Export to Excel" id="export_btn" class="btn btn-default" />
                <input type="button" name="pdf" value="Export to PDF" id="pdf_btn" class="btn btn-default" />
                <input type="button" name="print" value="Print" id="print_btn" class="btn btn-default" />
            }
        </div>
    </div>
}

@if (Model.RowList.Count > 0)
{
    <div class="row top-space-10">
        <div id="rptgrid">
        </div>
    </div>

    <script>

        var rows = [];
        @{
    for (int i = 0; i < Model.RowList.Count; i++)
        {
            <text>
        var entryArray = [];
        </text>

            for (int j = 0; j < Model.RowList[i].ColValue.Count; j++)
            {
                <text>
        entryArray.push('@Model.RowList[i].ColValue[j]');
        </text>
            }

            <text>
        rows.push({
            entries: entryArray
        });
        </text>
        }
    }

        $(document).ready(function () {
            var columns = [];
            @{
            for (int i = 0; i < Model.ColumnList.Count; i++)
            {
                <text>
            var IsHidden = false;
            var Isgroup = false;
            var IsSort = false;
            @if (Model.ColumnList[i].Ishidden)
                    {
                        <text>
            IsHidden = true;
            </text>
                    }
                    
             @if (Model.ColumnList[i].IsGroupable)
             {
                 <text>
                 Isgroup = true;
                 </text>
             }
            
                    @if (Model.ColumnList[i].IsSortable)
                    {
                        <text>
                        IsSort = true;
                        </text>
                    }

            columns.push({
                field: "entries[" + @i + "]",
                title: '@Model.ColumnList[i].ColumName',
                hidden: IsHidden,
                groupable: Isgroup,
                sortable: IsSort
            });
            </text>
            }
        }

            $("#rptgrid").kendoGrid({
                dataSource: {
                    data: rows,
                    pageSize: '@Model.defaultGridPageSize',
                    serverPaging: false,
                    serverFiltering: false,
                    serverSorting: false
                },
                pageable: {
                    refresh: true,
                    pageSizes: [@Model.gridPageSizes]
                },
                groupable: true,
                reorderable: true,
                resizable: true,
                columnMenu: true,
                filterable: true,
                editable: false,
                sortable: true,
                columns: columns
            });

            $('#export_btn').click(function () {
                var grid = $("#rptgrid").data("kendoGrid");
                grid.saveAsExcel();
            });

            $('#pdf_btn').click(function () {
                var grid = $("#rptgrid").data("kendoGrid");
                grid.saveAsPDF();
            });

            $('#print_btn').click(function () {
                printGrid()
            });

        });


        function printGrid() {
            var gridElement = $('#rptgrid');
            var printableContent = '';

            var htmlStart =
                    '<!DOCTYPE html>' +
                    '<html>' +
                    '<head>' +
                    '<meta charset="utf-8" />' +
                    '<title>' + "@Model.FileName" + '</title>' +
                    '<link href="http://kendo.cdn.telerik.com/2017.1.118/styles/kendo.common.min.css" rel="stylesheet" /> ' +
                    '<style>' +
                    'html { font: 11pt sans-serif; }' +
                    '.k-grid { border-top-width: 0; }' +
                    '.k-grid, .k-grid-content { height: auto !important; }' +
                    '.k-grid-content { overflow: visible !important; }' +
                    'div.k-grid table { table-layout: auto; width: 100% !important; }' +
                    '.k-grid .k-grid-header th { border-top: 1px solid; }' +
                    '.k-grouping-header, .k-grid-toolbar, .k-grid-pager > .k-link { display: none; }' +
                    // '.k-grid-pager { display: none; }' + // optional: hide the whole pager
                    '</style>' +
                    '</head>' +
                    '<body>';

            var htmlEnd =
                    '</body>' +
                    '</html>';

            var gridHeader = gridElement.children('.k-grid-header');
            //if (gridHeader[0]) {
            var thead = gridHeader.find('thead').clone().addClass('k-grid-header');
            var clonegridelement = gridElement.clone();
            var removeheaderelem = clonegridelement.children('.k-grid-header').remove().end();
            var gridtbodycontent = clonegridelement.children('.k-grid-content').find('table').first().children('tbody');
            var html = gridtbodycontent.before(thead);
            printableContent = html.end().end().end().end()[0].outerHTML;

            var win = window.open('', '', 'width=800, height=500, resizable=1, scrollbars=1');
            var doc = win.document.open();
            doc.write(htmlStart + printableContent + htmlEnd);
            doc.close();
            setTimeout(function () {
                win.print();
            }, 2000);
        }

    </script>
}