3ischools 20192012/KS_SmartChild/Models/Session.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS_SmartChild.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Session()
        {
            this.Alumni = new HashSet<Alumnus>();
            this.AttendanceUserCards = new HashSet<AttendanceUserCard>();
            this.CertificateUploads = new HashSet<CertificateUpload>();
            this.ClassSubjectTestActivities = new HashSet<ClassSubjectTestActivity>();
            this.GatePasses = new HashSet<GatePass>();
            this.IDCardTemplateSessions = new HashSet<IDCardTemplateSession>();
            this.OnlineRegnSetups = new HashSet<OnlineRegnSetup>();
            this.RCConsolidations = new HashSet<RCConsolidation>();
            this.RCExamTermStandards = new HashSet<RCExamTermStandard>();
            this.SessionAdmissionDetails = new HashSet<SessionAdmissionDetail>();
            this.Students = new HashSet<Student>();
            this.StudentClasses = new HashSet<StudentClass>();
        }
    
        public int SessionId { get; set; }
        public string Session1 { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsDefualt { get; set; }
        public string SessionAbbr { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alumnus> Alumni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceUserCard> AttendanceUserCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CertificateUpload> CertificateUploads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassSubjectTestActivity> ClassSubjectTestActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GatePass> GatePasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IDCardTemplateSession> IDCardTemplateSessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlineRegnSetup> OnlineRegnSetups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCConsolidation> RCConsolidations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RCExamTermStandard> RCExamTermStandards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionAdmissionDetail> SessionAdmissionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentClass> StudentClasses { get; set; }
    }
}

3ischools 20192012/KS_SmartChild/Controllers/SecurityController.cs
using BAL.BAL.Common;
using DAL.DAL.ActivityLogModule;
using DAL.DAL.CatalogMaster;
using DAL.DAL.Common;
using DAL.DAL.ErrorLogModule;
using DAL.DAL.MenuModel;
using DAL.DAL.SettingService;
using DAL.DAL.UserModule;
using DAL.DAL.AddressModule;
using DAL.DAL.StudentModule;
using DAL.DAL.StaffModule;
using DAL.DAL.GuardianModule;
using DAL.DAL.ContactModule;
using KSModel.Models;
using ViewModel.ViewModel.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Data;
using System.Web.Script.Serialization;
using System.Web.Configuration;
using DAL.DAL.Kendo;
using BAL.BAL.Security;
using ViewModel.ViewModel.Staff;
using DAL.DAL.Security;
using ViewModel.ViewModel.Student;
using DAL.DAL.DocumentModule;
using ViewModel.ViewModel.ContactInfo;


namespace KS_SmartChild.Controllers
{
    public class SecurityController : Controller
    {
        #region fields

        public int count = 0;
        private readonly IDropDownService _IDropDownService;
        private readonly ILogService _Logger;
        private readonly ICatalogMasterService _ICatalogMasterService;
        private readonly IActivityLogMasterService _IActivityLogMasterService;
        private readonly IActivityLogService _IActivityLogService;
        private readonly IUserService _IUserService;
        private readonly IUserManagementService _IUserManagementService;
        private readonly IWebHelper _WebHelper;
        private readonly ISchoolSettingService _ISchoolSettingService;
        private readonly INavigationService _INavigationService;
        private readonly ICustomEncryption _ICustomEncryption;
        private readonly IConnectionService _IConnectionService;
        private readonly IAddressMasterService _IAddressMasterService;
        private readonly IStudentService _IStudentService;
        private readonly IGuardianService _IGuardianService;
        private readonly IStaffService _IStaffService;
        private readonly IContactService _IContactService;
        private readonly IUserAuthorizationService _IUserAuthorizationService;
        private readonly ICommonMethodService _ICommonMethodService;
        private readonly IEncryptionService _IEncryptionService;
        private readonly IDocumentService _IDocumentService;
        private readonly IExportHelper _IExportHelper;
        #endregion

        #region ctor

        public SecurityController(IDropDownService IDropDownService,
            ILogService Logger,
            ICatalogMasterService ICatalogMasterService,
            IActivityLogMasterService IActivityLogMasterService,
            IActivityLogService IActivityLogService,
            IUserService IUserService,
            IUserManagementService IUserManagementService,
            IConnectionService IConnectionService,
            IWebHelper WebHelper,
            ISchoolSettingService ISchoolSettingService,
            INavigationService INavigationService,
            ICustomEncryption ICustomEncryption, IAddressMasterService IAddressMasterService, IStudentService IStudentService,
            IGuardianService IGuardianService, IStaffService IStaffService, IContactService IContactService,
            IUserAuthorizationService IUserAuthorizationService,
            ICommonMethodService ICommonMethodService,
            IEncryptionService IEncryptionService,
            IDocumentService IDocumentService,
            IExportHelper IExportHelper)
        {
            this._IDropDownService = IDropDownService;
            this._Logger = Logger;
            this._ICatalogMasterService = ICatalogMasterService;
            this._IActivityLogMasterService = IActivityLogMasterService;
            this._IActivityLogService = IActivityLogService;
            this._IUserService = IUserService;
            this._IUserManagementService = IUserManagementService;
            this._WebHelper = WebHelper;
            this._ISchoolSettingService = ISchoolSettingService;
            this._INavigationService = INavigationService;
            this._ICustomEncryption = ICustomEncryption;
            this._IConnectionService = IConnectionService;
            this._IAddressMasterService = IAddressMasterService;
            this._IStudentService = IStudentService;
            this._IGuardianService = IGuardianService;
            this._IStaffService = IStaffService;
            this._IContactService = IContactService;
            this._IUserAuthorizationService = IUserAuthorizationService;
            this._ICommonMethodService = ICommonMethodService;
            this._IEncryptionService =IEncryptionService;
            this._IDocumentService = IDocumentService;
            this._IExportHelper = IExportHelper;
        }

        #endregion

        #region utility

        public void SetSessionData(string name)
        {
            var user = _IUserService.GetUserByEmail(name);
            HttpContext.Session["UserId"] = user.UserName;

            var logininfo = _IUserService.GetAllUserLoginInfos(ref count, user.UserId).LastOrDefault();
            if (logininfo != null)
                HttpContext.Session["LoginInfoId"] = logininfo.LoginInfoId;
        }

        public string ConvertDate(DateTime Date)
        {
            string sdisplayTime = Date.ToString("dd/MM/yyyy");
            return sdisplayTime;
        }

        public string ConvertTime(TimeSpan time)
        {
            TimeSpan timespan = new TimeSpan(time.Hours, time.Minutes, time.Seconds);
            DateTime datetime = DateTime.Today.Add(timespan);
            string sdisplayTime = datetime.ToString("hh:mm tt");
            return sdisplayTime;
        }

        #endregion

        #region Methods

        #region User Role

        public UserRoleModel prepareuserrolemodel(UserRoleModel model)
        {
            model.AvailableContactType = _IDropDownService.ContactTypeList();
            var dynamicnavigationpath = "";
            var Is_Lite = _ISchoolSettingService.GetorSetSchoolData("Is_Lite", "0").AttributeValue == "1" ? true : false;
            if (Is_Lite)
                dynamicnavigationpath = "litenavigationpath";
            else
                dynamicnavigationpath = "navigationpath";
            var CustomNavigation = _ISchoolSettingService.GetorSetSchoolData("CustomNavigation", "0").AttributeValue == "1" ? true : false;
            //string file = "";
            var SchoolDbId = Convert.ToString(System.Web.HttpContext.Current.Session["SchoolId"]);
            ////get the Json filepath  
            //if (CustomNavigation)
            //{
            //    file = Server.MapPath(Convert.ToString(System.Web.Configuration.WebConfigurationManager.AppSettings[dynamicnavigationpath]) + "/" + SchoolDbId + "/" + Convert.ToString(WebConfigurationManager.AppSettings["userroletypejson"]));
            //}
            //else
            //{
            //    file = Server.MapPath(Convert.ToString(System.Web.Configuration.WebConfigurationManager.AppSettings[dynamicnavigationpath]) + Convert.ToString(WebConfigurationManager.AppSettings["userroletypejson"]));
            //}
            string file = Server.MapPath(Convert.ToString(System.Web.Configuration.WebConfigurationManager.AppSettings[dynamicnavigationpath])
                                + Convert.ToString(WebConfigurationManager.AppSettings["userroletypejson"]));
            ////deserialize JSON from file  
            string Json = System.IO.File.ReadAllText(file);
            JavaScriptSerializer ser = new JavaScriptSerializer();

            var list = ser.Deserialize<List<UserRoleTypeListModel>>(Json);
            if (list.Count > 0)
            {
                model.UserRoleTypeList.Add(new SelectListItem { Selected = false, Value = "", Text = "--Select--" });
                foreach (var item in list)
                    model.UserRoleTypeList.Add(new SelectListItem { Selected = false, Value = item.UserRoleTypeId.ToString(), Text = item.UserRoleType });

                var getRole = list.Where(x => x.UserRoleType.ToLower() == "admin").FirstOrDefault();
                model.UserTypeRoleId = getRole != null ? getRole.UserRoleTypeId.ToString() : "";
            }
            string file1 = "";
            if (CustomNavigation)
            {
                file1 = Server.MapPath(Convert.ToString(System.Web.Configuration.WebConfigurationManager.AppSettings[dynamicnavigationpath]) + "/" + SchoolDbId + "/" + Convert.ToString(WebConfigurationManager.AppSettings["leftjson"]));
            }
            else
            {
                file1 = Server.MapPath(Convert.ToString(System.Web.Configuration.WebConfigurationManager.AppSettings[dynamicnavigationpath]) + Convert.ToString(WebConfigurationManager.AppSettings["leftjson"]));
            }
            //string file1 = Server.MapPath(Convert.ToString(System.Web.Configuration.WebConfigurationManager.AppSettings[dynamicnavigationpath]) + Convert.ToString(WebConfigurationManager.AppSettings["leftjson"]));
            //deserialize JSON from file  
            var UserRoleNavigationItems = _INavigationService.GetAllUserRoleNavigationItems(ref count).ToList();
            var allactionpermissions = _IUserManagementService.GetAllUserRoleActionPermissions(ref count).ToList();
            // user role list
            // get all user role
            var userrolelist = _IUserService.GetAllUserRoles(ref count);
            foreach (var item in userrolelist)
            {
                UserRoleList UserRoleList = new UserRoleList();
                UserRoleList.UserRoleId = item.UserRoleId;

                //in admin case only
                UserRoleList.UserContactId = "";
                if (!string.IsNullOrEmpty(model.UserTypeRoleId))
                {
                    int UserRoleType_Id = Convert.ToInt32(model.UserTypeRoleId);
                    if (item.UserRole1.ToLower() == "administrator" && item.UserRoleTypeId == (int)UserRoleType_Id)

3ischools 20192012/KS_SmartChild/Views/Security/ChangeUserRole.cshtml
@model ViewModel.ViewModel.Security.ChangeUserRoleModel

<!-- Page Heading -->
<div class="row top-space-10 page-heading">
    @if (TempData["ErrorNotification"] != null && TempData["ErrorNotification"] != "")
    {
        <div class="col-md-12">
            <div class="error_notification"><i class="fa fa-ban"></i> @TempData["ErrorNotification"]</div>
        </div>
    }
    @if (TempData["SuccessNotification"] != null && TempData["SuccessNotification"] != "")
    {
        <div class="col-md-12">
            <div class="success_notification"><i class="fa fa-check"></i> @TempData["SuccessNotification"]</div>
        </div>
    }
</div>
<!-- //Page Heading -->
<style>
    .select2-container {
        width: 370px !important;
    }
</style>

<div class="row">
    <div class="container-fluid" style="max-width:400px;margin:60px auto;">
        @using (Html.BeginForm("ChangeUserRole", "Security", FormMethod.Post, new { @class = "form-vertical" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-group">
                <label class="custom-label">User Type:</label>
                @Html.DropDownListFor(model => model.UserTypeId, Model.UserTypeList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserTypeId, "", new { @class = "text-danger" })
            </div>
            <div class="form-group" id="classlist" hidden>
                <label class="custom-label">Class:</label>
                @Html.DropDownListFor(model => model.Classid, Model.ClassList, new { @class = "form-control js-example-templating" })
                @Html.ValidationMessageFor(model => model.Classid, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label class="custom-label">User:</label>
                @Html.DropDownListFor(model => model.UserId, Model.UserList, new { @class = "form-control js-example-templating" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <label class="custom-label">User Role:</label>
                @Html.DropDownListFor(model => model.UserRoleId, Model.UserRoleList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserRoleId, "", new { @class = "text-danger" })
            </div>

            <button type="button" class="btn btn-default pull-right" id="cancelinfo">
                Cancel
            </button>
            <button type="submit" class="btn btn-success pull-right" id="saveinfo" style="margin-right: 15px;">
                Save
                <i class="fa fa-floppy-o"></i>
            </button>
        }
    </div>
</div>



<script>

    $(".js-example-templating").select2({
    });

    $(document).on('change', '#UserTypeId', function () {
        if ($("#UserTypeId option:selected").text() == "Student") {
            $('#ks_loader').show();
            $("#classlist").show();
            $.ajax({
                type: "POST",
                url: '@Html.Raw(Url.Action("GetAllClasses", "Security"))',
                data: {},
                success: function (result) {
                    if (result.status == "success") {
                        $("#Classid").find('option').not(':first').remove()
                        if (result.ClassList.length > 0) {
                            $.each(result.ClassList, function () {
                                $('#Classid').append('<option value=' + this.Value + '>' + this.Text + '</option>')
                            })
                        }
                        $('#ks_loader').hide();
                    }
                },
                error: function (xhr, status) {
                    var err = "Error " + " " + status;
                    ToastMessage(err, "error", true, 5000);
                }
            });
        }
        else {
            $('#ks_loader').show();
            $("#Classid").find('option').not(':first').remove()
            $("#classlist").hide();
            if ($(this).val() != "") {
                $.ajax({
                    type: "POST",
                    url: '@Html.Raw(Url.Action("GetUsersAndUserRoles", "Security"))',
                    data: { "ContactTypeId": $(this).val() },
                    success: function (res) {
                        if (res.status == "success") {
                            $("#UserId").find('option').not(':first').remove()
                            $("#UserRoleId").find('option').not(':first').remove()
                            if (res.UserList.length > 0) {
                                $.each(res.UserList, function () {
                                    $('#UserId').append('<option value=' + this.Value + '>' + this.Text + '</option>')
                                })
                            }
                            if (res.UserRoleList.length > 0) {
                                $.each(res.UserRoleList, function () {
                                    $('#UserRoleId').append('<option value=' + this.Value + '>' + this.Text + '</option>')
                                })
                            }
                        }
                        else {
                            $("#UserId").find('option').not(':first').remove();
                            $("#UserRoleId").find('option').not(':first').remove();
                        }
                        $('#ks_loader').hide();
                    },
                    error: function (xhr, status) {
                        var err = "Error " + " " + status;
                        ToastMessage(err, "error", true, 5000);
                    }
                });
            }
            else {
                $("#UserId").find('option').not(':first').remove();
                $("#UserRoleId").find('option').not(':first').remove();
                return false;
            }
        }
    })

    $(document).on('change', '#Classid', function () {
        if ($(this).val() != "" && $("#UserTypeId").val() != "") {
            $('#ks_loader').show();
            $.ajax({
                type: "POST",
                url: '@Html.Raw(Url.Action("GetUsersAndUserRoles", "Security"))',
                data: { "ContactTypeId": $("#UserTypeId").val(), "ClassId": $(this).val() },
                success: function (res) {
                    if (res.status == "success") {
                        $("#UserId").find('option').not(':first').remove()
                        $("#UserRoleId").find('option').not(':first').remove()
                        if (res.UserList.length > 0) {
                            $.each(res.UserList, function () {
                                $('#UserId').append('<option value=' + this.Value + '>' + this.Text + '</option>')
                            })
                        }
                        if (res.UserRoleList.length > 0) {
                            $.each(res.UserRoleList, function () {
                                $('#UserRoleId').append('<option value=' + this.Value + '>' + this.Text + '</option>')
                            })
                        }
                    }
                    else {
                        $("#UserId").find('option').not(':first').remove();
                        $("#UserRoleId").find('option').not(':first').remove();
                    }
                    $('#ks_loader').hide();
                },
                error: function (xhr, status) {
                    var err = "Error " + " " + status;
                    ToastMessage(err, "error", true, 5000);
                }
            });
        }
        else {
            $("#UserId").find('option').not(':first').remove();
            $("#UserRoleId").find('option').not(':first').remove();
            return false;
        }
    })


    $(document).on('change', '#UserId', function () {
        if ($(this).val() != "") {
            $('#ks_loader').show();
            $.ajax({
                type: "POST",
                url: '@Html.Raw(Url.Action("GetCurrentUserRole", "Security"))',
                data: { "UserId": $(this).val() },
                success: function (res) {
                    if (res.status == "success") {
                        $('#UserRoleId').val(res.data);
                    }
                    else {
                        ToastMessage(err, "error", true, 5000);
                    }
                    $('#ks_loader').hide();
                },
                error: function (xhr, status) {
                    var err = "Error " + " " + status;
                    ToastMessage(err, "error", true, 5000);
                }
            });
        }
        else {
            return false;
        }
    })




    $("#saveinfo").click(function () {
        var isValid = validateUser();
        if (!isValid) {
            var validationaray = Uservalidationmessage.split('ε');
            for (var i = 0; i < validationaray.length - 1; i++) {
                ToastMessage(validationaray[i], "error", true, 5000);
            }
            $('#ks_loader').hide();
            return false;
        }
    })

    $("#cancelinfo").click(function () {
        $("#UserTypeId").val('');
        $("#Classid").val('').trigger('change');;
        $("#UserId").val('').trigger('change');;
        $("#UserRoleId").val('');
        $("#classlist").hide();
    })



    var Uservalid = true;
    var Uservalidationmessage = "";
    var Userctrlfocus = "";
    function validateUser() {
        Uservalid = true;
        Uservalidationmessage = "";
        Userctrlfocus = "";

        if ($('#UserTypeId').val() == "") {
            if (Userctrlfocus == "")
                Userctrlfocus = "#UserTypeId";
            Uservalidationmessage = Uservalidationmessage + "User Type required ε";
            Uservalid = false;
        }


        if ($('#UserId').val() == "") {
            if (Userctrlfocus == "")
                Userctrlfocus = "#UserId";
            Uservalidationmessage = Uservalidationmessage + "User required ε";
            Uservalid = false;
        }

        if ($('#UserRoleId').val() == "") {
            if (Userctrlfocus == "")
                Userctrlfocus = "#UserRoleId";
            Uservalidationmessage = Uservalidationmessage + "User Role required ε";
            Uservalid = false;
        }

        return Uservalid;
    }

</script>

3ischools 20192012/KS_SmartChild/Views/Security/URole.cshtml
@model ViewModel.ViewModel.Security.UserRoleModel

@{
    ViewBag.Title = "Manage UserRole";
}

<!-- Page Heading -->
<div class="row top-space-10 page-heading">
    @if (TempData["ErrorNotification"] != null && TempData["ErrorNotification"] != "")
    {
        <div class="col-md-12">
            <div class="error_notification"><i class="fa fa-ban"></i> @TempData["ErrorNotification"]</div>
        </div>
    }
    @if (TempData["SuccessNotification"] != null && TempData["SuccessNotification"] != "")
    {
        <div class="col-md-12">
            <div class="success_notification"><i class="fa fa-check"></i> @TempData["SuccessNotification"]</div>
        </div>
    }
    <div class="col-md-6">
        <h1>Manage UserRole <span style="font-size: 11px">( <i style="color: red;font-size: 8px;" class="fa fa-asterisk"></i> fields are required )</span></h1>
    </div>
</div>
<!-- //Page Heading -->
<!-- Page Controls -->
<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("URole", "Security", FormMethod.Post, new { @class = "form-horizontal ks-custom-form" }))
        {
            @Html.AntiForgeryToken()
            @Html.Partial("_CreateOrUpdate", Model)
        }
    </div>
</div>
<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    });
</script>

3ischools 20192012/KS_SmartChild/Views/Security/_CreateOrUpdateSession.cshtml
@model ViewModel.ViewModel.Security.SessionModel

@Html.HiddenFor(p => p.SessionId)
@Html.HiddenFor(p => p.StartDateToPost)
@Html.HiddenFor(p => p.EndDateToPost)
<div class="row  top-space-10" id="addUpdatefields">
    <div class="col-md-12">
        <div class="col-md-2">
            <label>Session</label>
            @Html.TextBoxFor(model => model.Session, null, new { @class = "form-control", @placeholder = "yyyy-yyyy", @maxlength = "9" })
            <!-- Error Message -->
            <div class="error-message" hidden>
                <i class="fa fa-exclamation-triangle"></i>
                @Html.ValidationMessageFor(model => model.Session)
            </div>
            <!-- //Error Message -->
        </div>
        <div class="col-md-2">
            <label>Start Date </label>
            @Html.TextBoxFor(model => model.StartDate, null, new { @class = "form-control", @placeholder = "dd/MM/yyyy", @maxlength = "12" })
            <!-- Error Message -->
            <div class="error-message" hidden>
                <i class="fa fa-exclamation-triangle"></i>
                @Html.ValidationMessageFor(model => model.StartDateToPost)
            </div>
            <!-- //Error Message -->
        </div>
        <div class="col-md-2">
            <label>End Date </label>
            @Html.TextBoxFor(model => model.EndDate, null, new { @class = "form-control", @placeholder = "dd/MM/yyyy", @maxlength = "12" })
            <!-- Error Message -->
            <div class="error-message" hidden>
                <i class="fa fa-exclamation-triangle"></i>
                @Html.ValidationMessageFor(model => model.EndDateToPost)
            </div>
            <!-- //Error Message -->
        </div>
        <div class="col-md-2 top-space-20" id="check"  hidden>
            <label>Is Default </label>
            @Html.CheckBoxFor(model => model.IsDetault)
        </div>
        <div class="col-md-3 top-space-20">
            @*@if (Model.IsAuthToAdd) {*@ 
            <button type="submit" name="save" class="btn btn-default" id="save-session">
                <i class="fa fa-floppy-o"></i>
                Save
            </button>@*}*@
            <button type="button" name="cancel" class="btn btn-default" id="cancel">
                Cancel
            </button>
        </div>
    </div>
</div>