3ischools 20192012/KS_SmartChild/Models/BoardingPoint.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS_SmartChild.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoardingPoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BoardingPoint()
        {
            this.BoardingPointFees = new HashSet<BoardingPointFee>();
            this.BusRouteDetails = new HashSet<BusRouteDetail>();
            this.Tpt_RouteTransitDetail = new HashSet<Tpt_RouteTransitDetail>();
            this.TptFacilities = new HashSet<TptFacility>();
        }
    
        public int BoardingPointId { get; set; }
        public string BoardingPoint1 { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<decimal> TransportFee_1 { get; set; }
        public Nullable<decimal> TransportFee_2 { get; set; }
        public Nullable<int> FeeFrequencyId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoardingPointFee> BoardingPointFees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BusRouteDetail> BusRouteDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tpt_RouteTransitDetail> Tpt_RouteTransitDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TptFacility> TptFacilities { get; set; }
    }
}

3ischools 20192012/KS_SmartChild/Controllers/TransportController.cs
using BAL.BAL.Common;
using BAL.BAL.Security;
using DAL.DAL.ActivityLogModule;
using DAL.DAL.AddressModule;
using DAL.DAL.CatalogMaster;
using DAL.DAL.Common;
using DAL.DAL.ContactModule;
using DAL.DAL.ErrorLogModule;
using DAL.DAL.FeeModule;
using DAL.DAL.GuardianModule;
using DAL.DAL.Kendo;
using DAL.DAL.SettingService;
using DAL.DAL.StudentModule;
using DAL.DAL.TransportModule;
using DAL.DAL.UserModule;
using KSModel.Models;
using ViewModel.ViewModel.API;
using ViewModel.ViewModel.Student;
using ViewModel.ViewModel.Transport;
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace KS_SmartChild.Controllers
{
    public class TransportController : Controller
    {
        #region fields

        public int count = 0;
        private readonly IDropDownService _IDropDownService;
        private readonly ILogService _Logger;
        private readonly ICatalogMasterService _ICatalogMasterService;
        private readonly IStudentService _IStudentService;
        private readonly IActivityLogMasterService _IActivityLogMasterService;
        private readonly IActivityLogService _IActivityLogService;
        private readonly IUserService _IUserService;
        private readonly IConnectionService _IConnectionService;
        private readonly IWebHelper _WebHelper;
        private readonly IBusService _IBusService;
        private readonly ITransportService _ITransportService;
        private readonly ISchoolSettingService _ISchoolSettingService;
        private readonly IUserAuthorizationService _IUserAuthorizationService;
        private readonly ICustomEncryption _ICustomEncryption;
        private readonly IContactService _IContactService;
        private readonly IAddressMasterService _IAddressMasterService;
        private readonly IGuardianService _IGuardianService;
        private readonly IFeeService _IFeeService;
        private readonly IModuleVersionService _IModuleVersionService;
        private readonly IExportHelper _IExportHelper;
        private readonly IStudentMasterService _IStudentMasterService;
        #endregion

        #region ctor

        public TransportController(IDropDownService IDropDownService,
            ILogService Logger,
            ICatalogMasterService ICatalogMasterService,
            IStudentService IStudentService,
            IActivityLogMasterService IActivityLogMasterService,
            IActivityLogService IActivityLogService,
            IUserService IUserService,
            IConnectionService IConnectionService,
            IWebHelper WebHelper,
            IBusService IBusService,
            ITransportService ITransportService,
            ISchoolSettingService ISchoolSettingService,
            IUserAuthorizationService IUserAuthorizationService,
            ICustomEncryption ICustomEncryption,
            IContactService IContactService,
            IAddressMasterService IAddressMasterService,
            IGuardianService IGuardianService,
            IFeeService IFeeService, IModuleVersionService IModuleVersionService,
            IExportHelper IExportHelper, IStudentMasterService IStudentMasterService)
        {
            this._IDropDownService = IDropDownService;
            this._Logger = Logger;
            this._ICatalogMasterService = ICatalogMasterService;
            this._IStudentService = IStudentService;
            this._IActivityLogMasterService = IActivityLogMasterService;
            this._IActivityLogService = IActivityLogService;
            this._IUserService = IUserService;
            this._IConnectionService = IConnectionService;
            this._WebHelper = WebHelper;
            this._IBusService = IBusService;
            this._ITransportService = ITransportService;
            this._ISchoolSettingService = ISchoolSettingService;
            this._IUserAuthorizationService = IUserAuthorizationService;
            this._ICustomEncryption = ICustomEncryption;
            this._IContactService = IContactService;
            this._IAddressMasterService = IAddressMasterService;
            this._IGuardianService = IGuardianService;
            this._IFeeService = IFeeService;
            this._IExportHelper = IExportHelper;
            this._IModuleVersionService = IModuleVersionService;
            this._IStudentMasterService = IStudentMasterService;
        }

        #endregion

        #region utility

        public void SetSessionData(string name)
        {
            var user = _IUserService.GetUserByEmail(name);
            HttpContext.Session["UserId"] = user.UserName;

            var logininfo = _IUserService.GetAllUserLoginInfos(ref count, user.UserId).LastOrDefault();
            if (logininfo != null)
                HttpContext.Session["LoginInfoId"] = logininfo.LoginInfoId;
        }

        public string ConvertDate(DateTime Date)
        {
            string sdisplayTime = Date.ToString("dd/MM/yyyy");
            return sdisplayTime;
        }

        public DateTime FormatDate(string Date)
        {
            string sdisplayTime = Date.Trim('"');
            var dd = Date.Split('/');
            sdisplayTime = dd[1] + "-" + dd[0] + "-" + dd[2];
            return Convert.ToDateTime(sdisplayTime);
        }

        public string ConvertTime(TimeSpan time, bool Is24HourFormat = false)
        {
            TimeSpan timespan = new TimeSpan(time.Hours, time.Minutes, time.Seconds);
            DateTime datetime = DateTime.Today.Add(timespan);
            string sdisplayTime = "";
            if (Is24HourFormat)
                sdisplayTime = datetime.ToString("HH:mm");
            else
                sdisplayTime = datetime.ToString("hh:mm tt");

            return sdisplayTime;
        }

        #endregion

        #region Methods

        #region Transport Route

        public ActionResult FilterBusRoute(TransportRouteModel model)
        {
            try
            {
                var session = _ICatalogMasterService.GetCurrentSession();
                var allroutes = _IBusService.GetAllBusRoutes(ref count, Routestatus: true);


                if (model.BoardingPointId != null && model.BoardingPointId > 0)
                {
                    var getBusRouteDetails = _IBusService.GetAllBusRouteDetails(ref count, status: true, BoardingPointId: model.BoardingPointId);
                    allroutes = allroutes.Join(getBusRouteDetails, a => a.BusRouteId, b => b.BusRouteId, (a, b) => new { a })
                                          .Select(x=>x.a).ToList();
                }

                if (model.SessionId != null && model.SessionId>0)
                {
                    session = _ICatalogMasterService.GetAllSessions(ref count).Where(m => m.SessionId == model.SessionId).FirstOrDefault();
                    allroutes = allroutes.Where(m => m.EffectiveDate <= session.EndDate && m.EndDate>=session.StartDate||m.EffectiveDate>=session.StartDate&&m.EffectiveDate<=session.EndDate||m.EffectiveDate<=session.EndDate&&m.EndDate==null).ToList();
                    
                    //allroutes = allroutes.Where(m => m.EndDate == null || m.EndDate >= session.StartDate).ToList();
                  //  allroutes = allroutes.Where(m =>m.EffectiveDate<=session.EndDate).ToList();
                   // allroutes = allroutes.Where(m => m.EndDate == null || m.EndDate>=session.StartDate).ToList();
                
                }

                
                var StuStatus = _IStudentMasterService.GetAllStudentStatus(ref count, "Active").FirstOrDefault();
                var AllTptFaciliTies = _ITransportService.GetAllTptFacilitys(ref count);
                var current_Session = _ICatalogMasterService.GetCurrentSession();
                var AllStudentClass = _IStudentService.GetAllStudentClasss(ref count, SessionId: current_Session.SessionId);
                var AllBusRouteDetail = _IBusService.GetAllBusRouteDetails(ref count);
                if (model.SessionId > 0)
                    current_Session.SessionId = model.SessionId;

                foreach (var item in allroutes.Distinct())
                {
                    BusRouteList BusRouteList = new BusRouteList();
                    // get bus route bus detail
                    var tptroutedetail = item.TptRouteDetails.ToList();

                    item.BusRouteDetails.Where(x => x.BoardingPointId == model.BoardingPointId).ToList();
                    var tptroutebus = tptroutedetail.Where(t => t.BusId != null && t.EndDate == null).FirstOrDefault();
                    BusRouteList.BusId = tptroutebus != null ? (int)tptroutebus.BusId : 0;
                    BusRouteList.BusName = tptroutebus != null ? tptroutebus.Bus.BusNo : "";
                    // get bus route driver detail
                    var tptroutedriver = tptroutedetail.Where(t => t.DriverId != null && t.EndDate == null).FirstOrDefault();
                    BusRouteList.DriverId = tptroutedriver != null ? (int)tptroutedriver.DriverId : 0;
                    BusRouteList.DriverName = tptroutedriver != null ? tptroutedriver.TptDriver.DriverName : "";
                    BusRouteList.TptRouteDetailId= tptroutedriver != null ? tptroutedriver.TptRouteDetailId.ToString() : "";
                    BusRouteList.BusRouteId = item.BusRouteId;
                    BusRouteList.EncBusRouteId = _ICustomEncryption.base64e(item.BusRouteId.ToString());
                    BusRouteList.BusRouteName = item.BusRoute1;
                    BusRouteList.BusRouteStatus = (bool)item.RouteStatus;
                    BusRouteList.BusRouteNo = item.RouteNo;
                    BusRouteList.EffectiveDate = ConvertDate(item.EffectiveDate.Value);
                    BusRouteList.dtEffectiveDate = (DateTime)item.EffectiveDate;
                    BusRouteList.dtEndDate = item.EndDate;

3ischools 20192012/KS_SmartChild/Views/Transport/BoardingPoint.cshtml
@model ViewModel.ViewModel.Transport.BoardingPointModel
@{
    ViewBag.Title = "BoardingPoint";
}
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB1m5beHM39zUD1IrCyUG2cIM6tkbM6cjc&libraries=geometry" type="text/javascript"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB1m5beHM39zUD1IrCyUG2cIM6tkbM6cjc&libraries=places" type="text/javascript"></script>
<script src="~/Scripts/jquery.ui.map.js"></script>


<!-- Page Heading -->
<div class="row top-space-10 page-heading">
    @if (TempData["ErrorNotification"] != null && TempData["ErrorNotification"] != "")
    {
        <div class="col-md-12">
            <div class="error_notification"><i class="fa fa-ban"></i> @TempData["ErrorNotification"]</div>
        </div>
    }
    @if (TempData["SuccessNotification"] != null && TempData["SuccessNotification"] != "")
    {
        <div class="col-md-12">
            <div class="success_notification"><i class="fa fa-check"></i> @TempData["SuccessNotification"]</div>
        </div>
    }
    @*<div class="col-md-12 error_notification" hidden>
        <div><i class="fa fa-ban"></i><span></span></div>
    </div>
    <div class="col-md-12 success_notification" hidden>
        <div><i class="fa fa-check"></i><span></span></div>
    </div>*@
    <div class="col-md-6">
        <h1 id="clshead">Manage Boarding Point</h1>
    </div>
    <div class="col-md-6 text-right">
        <a href="javascript:void(0)" id="AddNewBoardingPoint" class="btn btn-xs btn-default">Add New</a>
        <a href="javascript:void(0)" id="exportToExcelBoardingPoint" class="btn btn-xs btn-default">ExportToExcel</a>
        <a href="javascript:void(0)" id="printBoardingPoint" class="btn btn-xs btn-default">Print</a>
        <a title="Close Open Boarding Points" class="closeOpenBoardingPoint  btn btn-xs btn-default" href="javascript:void()"><i class="fa fa-ban" aria-hidden="true"></i></a>
    </div>
</div>
<!-- //Page Heading -->
<!-- Page Controls -->

<div class="modal-popup" id="clsBoardingPointmodal" hidden style="">
    <div class="modal-popup-body" style="width: 70%;">
        <div class="modal-content" style="padding: 0 0 10px 0;">
            <div class="modal-header">
                <h4 class="modal-title">Close Open Boarding Point</h4>
            </div>
            <div class="modal-body" style="overflow-x:auto">
                <div class="row">
                    <div class="col-md-12">
                        <div class="col-md-4">
                            <label class=" control-label">Close Date : </label>
                            <input style="width:76%;height: 31px" id="clsBoardingPointCloseDate" title="datepicker" />
                        </div>
                        <div class="col-md-4" style="margin-top: 22px;">
                            <button type="button" id="saveClsBoardingPoint" class="btn btn-danger">Save</button>
                        </div>
                    </div>
                    <div class="col-md-12 clsTableDiv" style="display:none;margin-top: 10px;">
                        <table id="" class="table table-bordered table-responsive table-striped table-condensed">
                            <thead class="thead-default">
                                <tr>
                                    <th><input type="checkbox" id="clsBoardingPointFeecheckedAll" /></th>
                                    <th>BoarDingPoint</th>
                                    @*<th>Latitude</th>
                                    <th>Longitude</th>*@
                                    <th>Pick & Drop Fee</th>
                                    <th>Pick Or Drop Fee</th>
                                    <th>Effective Date</th>
                                    <th>End Date</th>
                                </tr>
                            </thead>
                            <tbody id="clsBoardingPointTable"></tbody>
                        </table>
                    </div>
                    <div class="col-md-12 clsBoardingPointNodataDiv" style="display:none;margin-top: 10px;">
                        <label>No Data Found</label>
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="closeClsBoardingPointmodal" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("BoardingPoint", "Transport", FormMethod.Post, new { @class = "form-horizontal ks-custom-form" }))
        {
            
            @Html.AntiForgeryToken()
            @Html.Partial("_CreateOrUpdateBoardingPoint", Model)
        }
    </div>
</div>

<script>
    $("#clsBoardingPointCloseDate").attr("readonly", false);
    $("#clsBoardingPointCloseDate").kendoDatePicker({
        format: "dd/MM/yyyy"
    })
    $("#clsBoardingPointCloseDate").attr("readonly", true);

    $(".closeOpenBoardingPoint").click(function () {
        $("#clsBoardingPointTable").html("");
        $("#clsBoardingPointCloseDate").val("");
            $('#ks_loader').show();
            $.ajax({
                type: "Post",
                url: '@Html.Raw(Url.Action("OpenBoardingPointList", "Transport"))',
                data: { },
                success: function (result) {
                    if (result.BoardingPointList.length > 0) {
                        var html = "";
                        $.each(result.BoardingPointList, function (key) {
                            html += "<tr>";
                            html += '<td><input type="checkbox" class="checkedAll" /></td>'
                            html += '<td style="display: none" class="clsBRI">' + result.BoardingPointList[key].BoardingPointFeeId + '</td>'
                            html += '<td >' + result.BoardingPointList[key].BoardingPoint1 + '</td>'
                            //html += '<td >' + result.BoardingPointList[key].Latitude + '</td>'
                            //html += '<td class="">' + result.BoardingPointList[key].Longitude + '</td>'
                            html += '<td class="">' + result.BoardingPointList[key].TransportFee_1 + '</td>'
                            html += '<td class="">' + result.BoardingPointList[key].TransportFee_2 + '</td>'
                            html += '<td class="clsCloseED">' + result.BoardingPointList[key].strEffDate + '</td>'
                            html += '<td class="">' + result.BoardingPointList[key].EndDate!=null ? result.BoardingPointList[key].EndDate : "" + '</td>'
                        })
                        $("#clsBoardingPointTable").append(html);
                        $(".clsTableDiv").show();
                        $(".closeDateDiv").show();
                        $('#ks_loader').hide();
                        $('#clsBoardingPointmodal').show();
                    } else {
                        $('#clsBoardingPointmodal').hide();
                        ToastMessage("No Data", "error", true, 5000);
                        $('#ks_loader').hide();
                    }
                },
                error: function (xhr, status, data) {
                    var err = "Error " + " " + data;
                    ToastMessage(err, "error", true, 5000);
                    $('#ks_loader').hide();
                }
            });
    })

    $("#closeClsBoardingPointmodal").click(function () {
        $("#clsBoardingPointmodal").hide();

    })
    $("#clsBoardingPointFeecheckedAll").click(function () {
        if ($(this).prop("checked") == true) {
            $(".checkedAll").prop("checked", true);
        }
        else {
            $(".checkedAll").removeAttr('checked');
        }
    })
    $("#saveClsBoardingPoint").click(function () {
        $('#ks_loader').show();
        if ($("#clsBoardingPointCloseDate").val() == "" || $("#clsBoardingPointCloseDate").val() == null) {
            $('#ks_loader').hide();
            ToastMessage("Please Select Close Date Ist", "error", true, 5000);
            return false;
        }

        var closeDatestring = $("#clsBoardingPointCloseDate").val();
        var closedatearray = closeDatestring.split('/');
        var CFormatCloseDate = closedatearray[1] + "/" + closedatearray[0] + "/" + closedatearray[2];
        var CloseDate = new Date(closedatearray[1] + "/" + closedatearray[0] + "/" + closedatearray[2]);

        var BoardingPointFeeIds = "";
        var IsGreater = true;
        $(".checkedAll").each(function (i) {
            if ($(this).prop("checked") == true) {

                if (BoardingPointFeeIds != "") {
                    BoardingPointFeeIds += ";";
                }

                BoardingPointFeeIds += $(this).parent().parent().find(".clsBRI").text();

                var effectivestring = $(this).parent().parent().find(".clsCloseED").text();
                var datearry = effectivestring.split('/');
                var EffectiveDate = new Date(datearry[1] + "/" + datearry[0] + "/" + datearry[2]);

                if (CloseDate <= EffectiveDate) {
                    IsGreater = false;
                    return false;
                }
            }
        })
        if (!IsGreater) {
            $('#ks_loader').hide();
            ToastMessage("Close Date Should Be Greater Than Effective Dates Of Selected Boarding Points", "error", true, 5000);
            return false;
        }
        if (BoardingPointFeeIds == "") {
            $('#ks_loader').hide();
            ToastMessage("Please Select Atleast One Boarding Point", "error", true, 5000);
            return false;
        }

        $.ajax({
            type: "Post",
            url: '@Html.Raw(Url.Action("SaveCloseBoardingPoints", "Transport"))',
            data: { "CloseDate": CFormatCloseDate, "BoardingPointFeeIds": BoardingPointFeeIds },
            success: function (result) {
                if (result.status == "success") {
                    ToastMessage(result.msg, "success", true, 5000);
                    $('#ks_loader').hide();
                    $(".closeOpenBoardingPoint").trigger('click');
                    var grid = $('#boardingpoint-grid').data('kendoGrid');
                    grid.dataSource.page(1);
                }
                else {
                    ToastMessage(result.msg, "error", true, 5000);
                    $('#ks_loader').hide();
                }
            },
            error: function (xhr, status, data) {
                var err = "Error " + " " + data;
                ToastMessage(err, "error", true, 5000);
                $('#ks_loader').hide();
            }
        });
    })
    $(document).on('click', '.checkedAll', function () {
        if ($(this).prop("checked") == false) {
            $("#clsBoardingPointFeecheckedAll").removeAttr('checked');
        }
    })
</script>